version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.13
    working_directory: /go/src/github.com/flowerinthenight/athena2csv/
    steps:
    - checkout
    - run:
        name: build
        shell: /bin/bash
        command: |
          GO111MODULE=on GOFLAGS=-mod=vendor go build -v
